### ISSUE TITLE
cos_client.py is insecurely using HTTP by default

### ISSUE THREAD

**Issue by rtener** [tencentyun/coscmd#132]
Hi. I lead the security team at Evernote.

The default value for `CosConfig(schema=http)` is insecure. You are encouraging Qcloud users to transfer files with no transport encryption. QCloud customers expect data to be secure by default, so you need to change the default value to `schema=https`.

-Rich Tener

**Comment by lewzylu** [comment]
Yeah, https will be used by default in the next version. Thank you for your comments
