### ISSUE TITLE
Delta update for coscmd upload -r

### ISSUE THREAD

**Issue by htfy96** [tencentyun/coscmd#140]
Usually, only a small portion of files are changed and it is time-consuming to upload all files in advance.

**Comment by lewzylu** [comment]
Now you can use upload -s to skip the same file, provided that the previous file was also uploaded using coscmd. (Because the latest coscmd upload will carry the header of x-cos-meta-md5 to verify if the file is the same)

**Comment by htfy96** [comment]
Thanks. It works now. Probably it would be better to check all files' status in parallel.

**Comment by htfy96** [comment]
Fixed by #149
