### ISSUE TITLE
coscmd 能不能像 awscli 一样支持的更友好一些呢？

### ISSUE THREAD

**Issue by deanchina** [tencentyun/coscmd#169]
比如 
  1. 能不能支持ls ， cp， 不要只给人一个list, copy 的命令， 使用的人基本都有Linux基础的，按linux规范来不好吗？
  2. 错误或是帮助 输出能不能好一些也按标准做。
  3. cos.conf  里， 配置默认的bucket   -- 这个 真的不知道怎么想的？？  不配置默认的bucket还不让用，还直接是配置错误。

# coscmd download cdb/bbs20180807_v2.utf8 .
Download cos://backup/cdb/bbs20180807_v2.utf8   =>   .
Downloading .
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.38G/3.38G [01:15<00:00, 44.7MB/s]
Completing mget
[Errno 21] Is a directory: u'.'
Mget file failure
这样一个命令， 我都不知道错在哪了。

**Comment by lewzylu** [comment]
1.用户很多都是技术小白，部分甚至是windos使用者。
2.请参考下sample
coscmd download <cospath> <localpath>  //命令格式
coscmd download bbb/123.txt /home/aaa/111.txt  //操作示例
coscmd download bbb/123.txt /home/aaa/  //操作示例
如果要下载到当前目录， local_path就应该为 './'   , '.'在linux里被理解为路径

**Comment by deanchina** [comment]
不能做下兼容？  就直接close掉？   腾讯云厉害了，硬气

**Comment by lewzylu** [comment]
Download cos://backup/cdb/bbs20180807_v2.utf8 => .   兼容如何区分你是想重命名为'.'  ,还是下载到当前目录
