### ISSUE TITLE
用pip安装了，成功上传文件，但是bucket中找不到该文件

### ISSUE THREAD

**Issue by 1265578519** [tencentyun/coscmd#180]
[root@217 home]# coscmd upload /home/123.mp4 123.mp4
Upload /home/123.mp4   =>   cos:///123.mp4
[root@217 home]# 

也没有报错

**Comment by lewzylu** [comment]
能贴一下配置文件的内容吧，不需要不需要密钥

**Comment by lewzylu** [comment]
有带上appid吗

**Comment by lewzylu** [comment]
bucketname 应该填成 bucket-appid的格式，像bucket-1251633352，这样

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/44722407-8b954c80-aaff-11e8-80bb-1316914e0dab.png)
在哪里可以看到appid，我没有找到
是写bucketname-1251633352？还是bucket-1251633352。。你们这文档也写的太不详细

**Comment by lewzylu** [comment]
![image](https://user-images.githubusercontent.com/25299171/44759377-5f63e500-ab6c-11e8-94e6-76663bd2ca32.png)
 
appid可以在查看secretid和secretkey的地方查看

**Comment by 1265578519** [comment]
![1](https://user-images.githubusercontent.com/6442439/44779159-4d586580-abb1-11e8-83be-3c32b4eafa3d.png)
好的，找到了，晚上我在尝试下

**Comment by 1265578519** [comment]
Upload 41982247_01.jpg   =>   cos://sakura/123.jpg
/usr/lib/python2.6/site-packages/urllib3/util/ssl_.py:369: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/lib/python2.6/site-packages/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

出现了新的错误，不过文件测试已经上传成功。
![image](https://user-images.githubusercontent.com/6442439/44816677-89251680-ac15-11e8-9e5a-ff3fed2b3401.png)

**Comment by 1265578519** [comment]
'ascii' codec can't encode characters in position 6-11: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-17: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-22: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-28: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-33: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-39: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-50: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-50: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-56: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-61: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-67: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-72: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-78: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-84: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-89: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-95: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-100: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-106: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-111: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-117: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-123: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-128: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-134: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-139: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-145: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-151: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-156: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-162: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-167: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-173: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-178: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-184: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-189: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-195: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-200: ordinal not in range(128)

不过超过1MB的文件，上传提示这个。是什么问题。

**Comment by 1265578519** [comment]
[root@new_centos6 ~]# coscmd upload /root/lxzPV.mp4 video/lxzPV.mp41
Upload /root/lxzPV.mp4   =>   cos://sakura/video/lxzPV.mp41
  0%|                                                                                                                                                                                                            | 0.00/36.6M [00:00<?, ?B/s]'ascii' codec can't encode characters in position 6-11: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-17: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-22: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-28: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-33: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-39: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-44: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-50: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-56: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-61: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-67: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-72: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-78: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-84: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-89: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-95: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-100: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-106: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-111: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-117: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-123: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-128: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-134: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-139: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-145: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-151: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-156: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-161: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-167: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-172: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-178: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-184: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-189: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-195: ordinal not in range(128)
'ascii' codec can't encode characters in position 6-200: ordinal not in range(128)
[root@new_centos6 ~]# coscmd upload /root/lxzPV.mp4 video/lxzPV.mp41
Upload /root/lxzPV.mp4   =>   cos://sakura/video/lxzPV.mp41
Continue uploading from last breakpoint
36.7MB [00:00, 158GB/s]                                                                                                                                                                                                                      
Completing multiupload, please wait
[root@new_centos6 ~]# 

需要重复执行两次后才可以

**Comment by 1265578519** [comment]
coscmd -v
coscmd 1.8.5.7

话说上传进度条什么都没做啊。。
