### ISSUE TITLE
无法根据前缀删除文件。

### ISSUE THREAD

**Issue by 1265578519** [tencentyun/coscmd#183]
coscmd delete -rf backup/2018-08-28

Delete the remaining files again
The directory does not exist

删除不了

**Comment by 1265578519** [comment]
不加r参数也不行
Delete cos://test/backup/2018-08-28
看到空间还是有文件

**Comment by 1265578519** [comment]
有QQ吗？1265578519

**Comment by lewzylu** [comment]
暂时只支持删除/结尾的前缀，后续会支持任意前缀
