### ISSUE TITLE
update the version of pytz?

### ISSUE THREAD

**Issue by LionelZhao28** [tencentyun/coscmd#200]
the version of `pytz` is 2017.2, a very old one 
Many projects have updated it to new ones, eg. 2018.5, just like apache-beam
So if our project import `pytz` and apache-beam at the same time, the independence will be incompatible.
So could you update the version of pytz?
Thanks

**Comment by lewzylu** [comment]
requirement of pytz has been updated to >=  2017.2 at version 1.8.5.16

**Comment by LionelZhao28** [comment]
checked it.
Thanks a lot
