### ISSUE TITLE
Anonymous and auth by VPC doesn't work after 1.8.5.12

### ISSUE THREAD

**Issue by ChaiZhi** [tencentyun/coscmd#206]
We are using coscmd to list and download files for COS bucket auth by VPC id, the config in `.cos.conf` is:
```
anonymous = True
```

but from 1.8.5.12, list would return:
```
<?xml version='1.0' encoding='utf-8' ?>
<Error>
	<Code>InvalidAccessKeyId</Code>
	<Message>The Access Key Id you provided does not exist in our records</Message>
	<Resource>XXXXXXXXXXX</Resource>
	<RequestId>NWMwNjQ4YzFfNjNhYTk0MGFfMThhYl8yYmY3ZTk=</RequestId>
	<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTBjYzE2MjAxN2M1MzJiOTdkZjMxMDVlYTZjN2FiMmI0ZTI5NDE1MDVlZjUxMTI1NGUwOTAzYzUxYTRmMzdlNjE=</TraceId>
</Error>
```

by the way, `download` works fine.

**Comment by lewzylu** [comment]
This problem arises because these interfaces rely on cos-python-sdk-v5, but cos-python-sdk-v5 does not support this anonymity.
The bug has been fixed in the latest coscmd version (1.8.5.21). Please ensure that your cos-python-sdk-v5version >= 1.6.3
