### ISSUE TITLE
关于--sync参数的使用疑问

### ISSUE THREAD

**Issue by sc-syf** [tencentyun/coscmd#221]
据文档：

> 使用-s或者--sync参数，可以在下载文件夹时跳过本地已存在的相同文件（前提是下载文件夹是通过COSCMD的upload接口上传的，文件携带有 x-cos-meta-md5头部）

那么我是否可以，使用SDK上传文件，手动带上 x-cos-meta-md5 的头部。这样的话，再使用 coscmd 工具时， 能跳过本地已下载的文件么？

**Comment by lewzylu** [comment]
是可以的，只要cos上的文件带有正确的x-cos-meta-md5，coscmd的-s参数就会生效(不然校验不了文件的一致性)
