### ISSUE TITLE
.cos.log日志自定义大小申请

### ISSUE THREAD

**Issue by yuanaisha** [tencentyun/coscmd#257]
您好：

申请.cos.log日志文件上限扩容至1G，谢谢！

存储桶名称：st-rm-1255501786

所属地域	广州 （中国）（ap-guangzhou）

访问域名	https://st-rm-1255501786.cos.ap-guangzhou.myqcloud.com

**Comment by lewzylu** [comment]
well, we will support custom log size in the next iteration

**Comment by yuanaisha** [comment]
thx，请问这个版本可以先帮我们后台加大吗？

**Comment by lewzylu** [comment]
you can use  "coscmd --log_size 1000 --log_backup_count 10 upload a b" set log_size and backup_count in version 1.8.6.10
