### ISSUE TITLE
tqdm in coscmd is not thread-safe

### ISSUE THREAD

**Issue by xiacunshun** [tencentyun/coscmd#268]
When i try to download images with coscmd, it usually stuck. Then I add some output in the progress, it turns out that the program always stop at `self._pbar.update(chunk_len)`. So I remove the tqdm, and it fixed.

I guess because the tqdm is not thread-safe, when multi-thread runs.

**Comment by xiacunshun** [comment]
![image](https://user-images.githubusercontent.com/7437321/87020371-5206ef80-c206-11ea-9b1b-061ade576ba9.png)

**Comment by xiacunshun** [comment]
![image](https://user-images.githubusercontent.com/7437321/87020404-62b76580-c206-11ea-81c6-a9bee7b25889.png)

**Comment by lewzylu** [comment]
Thanks for your advice, I'll fixed soon
