### ISSUE TITLE
The action is not supported by the accelerate host

### ISSUE THREAD

**Issue by fajiaopaopao** [tencentyun/coscmd#274]
1. my cos bucket has enabled the function of global network acceleration, and coscmd version is `coscmd-1.8.6.20`
2. I run this command `coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET  -e cos.accelerate.myqcloud.com -m 30`
3. get error this log`'code': 'ActionAccelerateNotSupported', 'message': 'The action is not supported by the accelerate host.'`

**Comment by lewzylu** [comment]
Which interface do you use, some action is not supported with accelerate endpoint

**Comment by fajiaopaopao** [comment]
I found out that `delete` does not support accelerate endpoint, working well now.
