### ISSUE TITLE
删除面确认参数

### ISSUE THREAD

**Issue by wjangelking** [tencentyun/coscmd#70]
希望delete操作能增加`-y` 免确认参数
我在通过命令行匹配结果批量删除时，没法执行

**Comment by wjangelking** [comment]
我在通过命令行匹配结果批量删除时，没法执行

**Comment by Liuchang0812** [comment]
可以暂时使用 `echo "y" > coscmd delete xxx` 来绕过，后面版本会考虑该参数

**Comment by lewzylu** [comment]
最新版本delete已经增加 -f 免确认参数
